//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Ressources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Ressources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peter has a problem with his printer ähnelt.
        /// </summary>
        internal static string DescriptionSample {
            get {
                return ResourceManager.GetString("DescriptionSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die needhelp@example.com ähnelt.
        /// </summary>
        internal static string EmailSample {
            get {
                return ResourceManager.GetString("EmailSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An access token and a groupname are required for creating a session ähnelt.
        /// </summary>
        internal static string Error_AccessTokenAndGroupNameRequired {
            get {
                return ResourceManager.GetString("Error_AccessTokenAndGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An access token is required for getting the account&apos;s group-IDs ähnelt.
        /// </summary>
        internal static string Error_AccessTokenRequired {
            get {
                return ResourceManager.GetString("Error_AccessTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required input missing ähnelt.
        /// </summary>
        internal static string Error_RequiredInputMissing {
            get {
                return ResourceManager.GetString("Error_RequiredInputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample group ähnelt.
        /// </summary>
        internal static string GroupSample {
            get {
                return ResourceManager.GetString("GroupSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This demo application doesn&apos;t contain a client id, client secret or redirect url.
        ///Due this fact the authentication via OAuth is deactivated.
        ///
        ///If you wonna use OAuth please enter your own app data in the $safeprojectname$.Helper.OAuth class.
        ///
        ///If you don&apos;t have an app yet, you can create one in the TeamViewer Management Console under https://login.teamviewer.com ähnelt.
        /// </summary>
        internal static string IncompleteAppDataMessage {
            get {
                return ResourceManager.GetString("IncompleteAppDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tokens available -&gt; Access granted ähnelt.
        /// </summary>
        internal static string Label_TokenAvailable_AccessGranted {
            get {
                return ResourceManager.GetString("Label_TokenAvailable_AccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peter Needhelp ähnelt.
        /// </summary>
        internal static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon TeamViewer3_000 {
            get {
                object obj = ResourceManager.GetObject("TeamViewer3_000", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
